/// Reference data shipped with the app, generated from the backend's
/// database.py so the two cannot drift apart.
///
/// Foods are the searchable database for manual logging. Recipes are the
/// offline fallback for suggestions when the backend cannot be reached, which
/// is the third step of the fallback chain described in SYNC.md.

import 'models.dart';

const List<Food> seedFoods = [
  Food(id: 1, name: 'Chicken rice', brand: 'Hawker', serving: '1 plate',
      perServing: Nutrition(kcal: 607, carbsG: 78.0, proteinG: 34.0, fatG: 18.0)),
  Food(id: 2, name: 'Chicken rice, steamed', brand: 'Hawker', serving: '1 plate',
      perServing: Nutrition(kcal: 545, carbsG: 72.0, proteinG: 33.0, fatG: 12.0)),
  Food(id: 3, name: 'Nasi lemak', brand: 'Hawker', serving: '1 plate',
      perServing: Nutrition(kcal: 644, carbsG: 82.0, proteinG: 17.0, fatG: 27.0)),
  Food(id: 4, name: 'Char kway teow', brand: 'Hawker', serving: '1 plate',
      perServing: Nutrition(kcal: 744, carbsG: 76.0, proteinG: 23.0, fatG: 38.0)),
  Food(id: 5, name: 'Laksa', brand: 'Hawker', serving: '1 bowl',
      perServing: Nutrition(kcal: 590, carbsG: 55.0, proteinG: 20.0, fatG: 32.0)),
  Food(id: 6, name: 'Kaya toast', brand: 'Hawker', serving: '2 slices',
      perServing: Nutrition(kcal: 330, carbsG: 42.0, proteinG: 7.0, fatG: 14.0)),
  Food(id: 7, name: 'Roti prata, plain', brand: 'Hawker', serving: '1 piece',
      perServing: Nutrition(kcal: 224, carbsG: 26.0, proteinG: 5.0, fatG: 11.0)),
  Food(id: 8, name: 'Fish soup, sliced', brand: 'Hawker', serving: '1 bowl',
      perServing: Nutrition(kcal: 280, carbsG: 18.0, proteinG: 32.0, fatG: 8.0)),
  Food(id: 9, name: 'Yong tau foo, soup', brand: 'Hawker', serving: '1 bowl',
      perServing: Nutrition(kcal: 330, carbsG: 30.0, proteinG: 25.0, fatG: 11.0)),
  Food(id: 10, name: 'Prawn noodle soup', brand: 'Hawker', serving: '1 bowl',
      perServing: Nutrition(kcal: 400, carbsG: 52.0, proteinG: 22.0, fatG: 11.0)),
  Food(id: 11, name: 'Teh tarik', brand: 'Hawker', serving: '1 cup',
      perServing: Nutrition(kcal: 176, carbsG: 22.0, proteinG: 5.0, fatG: 7.0)),
  Food(id: 12, name: 'Rolled oats, dry', brand: 'Quaker', serving: '40 g',
      perServing: Nutrition(kcal: 150, carbsG: 27.0, proteinG: 5.0, fatG: 3.0)),
  Food(id: 13, name: 'Banana, medium', brand: null, serving: '1 fruit',
      perServing: Nutrition(kcal: 105, carbsG: 27.0, proteinG: 1.3, fatG: 0.4)),
  Food(id: 14, name: 'Apple, medium', brand: null, serving: '1 fruit',
      perServing: Nutrition(kcal: 95, carbsG: 25.0, proteinG: 0.5, fatG: 0.3)),
  Food(id: 15, name: 'Chicken breast, grilled', brand: null, serving: '100 g',
      perServing: Nutrition(kcal: 165, carbsG: 0.0, proteinG: 31.0, fatG: 3.6)),
  Food(id: 16, name: 'Salmon fillet, grilled', brand: null, serving: '150 g',
      perServing: Nutrition(kcal: 280, carbsG: 0.0, proteinG: 39.0, fatG: 13.0)),
  Food(id: 17, name: 'Tofu, firm', brand: null, serving: '100 g',
      perServing: Nutrition(kcal: 144, carbsG: 3.0, proteinG: 17.0, fatG: 9.0)),
  Food(id: 18, name: 'Brown rice, cooked', brand: null, serving: '1 cup',
      perServing: Nutrition(kcal: 216, carbsG: 45.0, proteinG: 5.0, fatG: 1.8)),
  Food(id: 19, name: 'White rice, cooked', brand: null, serving: '1 cup',
      perServing: Nutrition(kcal: 205, carbsG: 45.0, proteinG: 4.3, fatG: 0.4)),
  Food(id: 20, name: 'Broccoli, steamed', brand: null, serving: '100 g',
      perServing: Nutrition(kcal: 35, carbsG: 7.0, proteinG: 2.4, fatG: 0.4)),
  Food(id: 21, name: 'Eggs, boiled', brand: null, serving: '2 eggs',
      perServing: Nutrition(kcal: 155, carbsG: 1.1, proteinG: 12.6, fatG: 10.6)),
  Food(id: 22, name: 'Greek yoghurt, plain', brand: null, serving: '170 g',
      perServing: Nutrition(kcal: 100, carbsG: 6.0, proteinG: 17.0, fatG: 0.7)),
  Food(id: 23, name: 'Almonds', brand: null, serving: '25 g',
      perServing: Nutrition(kcal: 145, carbsG: 5.4, proteinG: 5.3, fatG: 12.5)),
  Food(id: 24, name: 'Peanut butter', brand: null, serving: '2 tbsp',
      perServing: Nutrition(kcal: 188, carbsG: 6.3, proteinG: 8.0, fatG: 16.0)),
  Food(id: 25, name: 'Milk, full fat', brand: null, serving: '250 ml',
      perServing: Nutrition(kcal: 150, carbsG: 12.0, proteinG: 8.0, fatG: 8.0)),
  Food(id: 26, name: 'Soy milk, unsweetened', brand: null, serving: '250 ml',
      perServing: Nutrition(kcal: 80, carbsG: 4.0, proteinG: 7.0, fatG: 4.0)),
  Food(id: 27, name: 'Iced tea, unsweetened', brand: null, serving: '1 glass',
      perServing: Nutrition(kcal: 13, carbsG: 3.2, proteinG: 0.0, fatG: 0.0)),
  Food(id: 28, name: 'Wholemeal bread', brand: null, serving: '2 slices',
      perServing: Nutrition(kcal: 160, carbsG: 28.0, proteinG: 8.0, fatG: 2.0)),
  Food(id: 29, name: 'Mixed vegetable salad', brand: null, serving: '1 bowl',
      perServing: Nutrition(kcal: 120, carbsG: 12.0, proteinG: 4.0, fatG: 6.0)),
  Food(id: 30, name: 'Protein shake, whey', brand: null, serving: '1 scoop',
      perServing: Nutrition(kcal: 120, carbsG: 3.0, proteinG: 24.0, fatG: 1.5)),
];

const List<Recipe> seedRecipes = [
  Recipe(id: 'local-1', name: 'Grilled salmon with quinoa', kcal: 612, carbsG: 48.0, proteinG: 41.0, fatG: 26.0, minutes: 25,
      allergens: ['fish'], dietTypes: ['high-protein'],
      ingredients: ['Salmon fillet 150 g', 'Quinoa, cooked 120 g', 'Broccoli 80 g', 'Olive oil 1 tbsp']),
  Recipe(id: 'local-2', name: 'Chickpea and spinach curry', kcal: 598, carbsG: 72.0, proteinG: 22.0, fatG: 21.0, minutes: 30,
      allergens: [], dietTypes: ['vegetarian', 'vegan', 'high-fibre'],
      ingredients: ['Chickpeas 240 g', 'Spinach 100 g', 'Coconut milk 80 ml', 'Brown rice 100 g']),
  Recipe(id: 'local-3', name: 'Chicken and broccoli stir-fry', kcal: 520, carbsG: 38.0, proteinG: 45.0, fatG: 18.0, minutes: 20,
      allergens: ['soy'], dietTypes: ['high-protein'],
      ingredients: ['Chicken breast 180 g', 'Broccoli 150 g', 'Soy sauce 1 tbsp', 'Rice 90 g']),
  Recipe(id: 'local-4', name: 'Tofu and vegetable noodles', kcal: 470, carbsG: 58.0, proteinG: 24.0, fatG: 15.0, minutes: 20,
      allergens: ['soy'], dietTypes: ['vegetarian', 'vegan'],
      ingredients: ['Firm tofu 150 g', 'Egg noodles 120 g', 'Mixed vegetables 150 g']),
  Recipe(id: 'local-5', name: 'Prawn and egg fried rice', kcal: 640, carbsG: 72.0, proteinG: 28.0, fatG: 24.0, minutes: 15,
      allergens: ['shellfish', 'egg'], dietTypes: [],
      ingredients: ['Prawns 120 g', 'Eggs 2', 'Rice 200 g', 'Peas 50 g']),
  Recipe(id: 'local-6', name: 'Peanut satay chicken', kcal: 680, carbsG: 34.0, proteinG: 44.0, fatG: 38.0, minutes: 35,
      allergens: ['peanut'], dietTypes: ['high-protein'],
      ingredients: ['Chicken thigh 200 g', 'Peanut sauce 60 g', 'Cucumber 80 g']),
  Recipe(id: 'local-7', name: 'Greek yoghurt bowl', kcal: 320, carbsG: 38.0, proteinG: 22.0, fatG: 8.0, minutes: 5,
      allergens: ['milk'], dietTypes: ['vegetarian', 'high-protein'],
      ingredients: ['Greek yoghurt 200 g', 'Berries 100 g', 'Oats 30 g', 'Honey 1 tsp']),
  Recipe(id: 'local-8', name: 'Lentil soup with bread', kcal: 430, carbsG: 62.0, proteinG: 21.0, fatG: 9.0, minutes: 30,
      allergens: ['gluten'], dietTypes: ['vegetarian', 'vegan', 'high-fibre'],
      ingredients: ['Red lentils 150 g', 'Carrot 80 g', 'Onion 60 g', 'Wholemeal bread 2 slices']),
  Recipe(id: 'local-9', name: 'Steamed fish with rice', kcal: 480, carbsG: 52.0, proteinG: 38.0, fatG: 10.0, minutes: 25,
      allergens: ['fish'], dietTypes: ['high-protein'],
      ingredients: ['White fish 180 g', 'Ginger', 'Rice 120 g', 'Bok choy 100 g']),
  Recipe(id: 'local-10', name: 'Beef and vegetable stew', kcal: 590, carbsG: 40.0, proteinG: 42.0, fatG: 26.0, minutes: 60,
      allergens: [], dietTypes: ['high-protein'],
      ingredients: ['Lean beef 180 g', 'Potato 150 g', 'Carrot 100 g', 'Celery 60 g']),
  Recipe(id: 'local-11', name: 'Chicken salad wrap', kcal: 425, carbsG: 40.0, proteinG: 32.0, fatG: 14.0, minutes: 10,
      allergens: ['gluten'], dietTypes: ['high-protein'],
      ingredients: ['Chicken breast 130 g', 'Tortilla 1', 'Lettuce 60 g', 'Yoghurt dressing']),
  Recipe(id: 'local-12', name: 'Black bean burrito bowl', kcal: 610, carbsG: 84.0, proteinG: 24.0, fatG: 18.0, minutes: 20,
      allergens: [], dietTypes: ['vegetarian', 'vegan', 'high-fibre'],
      ingredients: ['Black beans 200 g', 'Rice 150 g', 'Corn 60 g', 'Salsa 50 g']),
  Recipe(id: 'local-13', name: 'Baked cod with sweet potato', kcal: 465, carbsG: 48.0, proteinG: 36.0, fatG: 12.0, minutes: 35,
      allergens: ['fish'], dietTypes: ['high-protein'],
      ingredients: ['Cod 180 g', 'Sweet potato 200 g', 'Green beans 100 g', 'Olive oil 1 tbsp']),
  Recipe(id: 'local-14', name: 'Mushroom and barley risotto', kcal: 505, carbsG: 78.0, proteinG: 14.0, fatG: 14.0, minutes: 40,
      allergens: ['milk'], dietTypes: ['vegetarian', 'high-fibre'],
      ingredients: ['Pearl barley 150 g', 'Mushrooms 150 g', 'Parmesan 20 g', 'Stock 400 ml']),
  Recipe(id: 'local-15', name: 'Egg and avocado toast', kcal: 410, carbsG: 34.0, proteinG: 18.0, fatG: 23.0, minutes: 10,
      allergens: ['egg', 'gluten'], dietTypes: ['vegetarian'],
      ingredients: ['Eggs 2', 'Avocado half', 'Wholemeal bread 2 slices']),
  Recipe(id: 'local-16', name: 'Vegetable fried brown rice', kcal: 450, carbsG: 68.0, proteinG: 12.0, fatG: 14.0, minutes: 20,
      allergens: ['soy'], dietTypes: ['vegetarian', 'vegan'],
      ingredients: ['Brown rice 180 g', 'Mixed vegetables 150 g', 'Soy sauce 1 tbsp']),
  Recipe(id: 'local-17', name: 'Grilled chicken salad', kcal: 385, carbsG: 18.0, proteinG: 40.0, fatG: 16.0, minutes: 15,
      allergens: [], dietTypes: ['high-protein', 'low-carb'],
      ingredients: ['Chicken breast 180 g', 'Mixed leaves 100 g', 'Cherry tomatoes 80 g', 'Olive oil 1 tbsp']),
  Recipe(id: 'local-18', name: 'Tofu and vegetable curry', kcal: 520, carbsG: 58.0, proteinG: 22.0, fatG: 22.0, minutes: 30,
      allergens: ['soy'], dietTypes: ['vegetarian', 'vegan'],
      ingredients: ['Firm tofu 200 g', 'Coconut milk 150 ml', 'Mixed vegetables 200 g', 'Rice 100 g']),
  Recipe(id: 'local-19', name: 'Salmon and soba noodles', kcal: 560, carbsG: 52.0, proteinG: 38.0, fatG: 20.0, minutes: 25,
      allergens: ['fish', 'soy', 'gluten'], dietTypes: ['high-protein'],
      ingredients: ['Salmon 150 g', 'Soba noodles 120 g', 'Spring onion 40 g', 'Sesame oil 1 tsp']),
  Recipe(id: 'local-20', name: 'Minestrone with beans', kcal: 395, carbsG: 58.0, proteinG: 18.0, fatG: 9.0, minutes: 35,
      allergens: ['gluten'], dietTypes: ['vegetarian', 'high-fibre'],
      ingredients: ['Cannellini beans 200 g', 'Pasta 60 g', 'Tomato 300 g', 'Carrot 80 g']),
  Recipe(id: 'local-21', name: 'Turkey and vegetable chilli', kcal: 470, carbsG: 44.0, proteinG: 40.0, fatG: 14.0, minutes: 45,
      allergens: [], dietTypes: ['high-protein', 'high-fibre'],
      ingredients: ['Turkey mince 200 g', 'Kidney beans 150 g', 'Tomato 300 g', 'Pepper 100 g']),
  Recipe(id: 'local-22', name: 'Roasted vegetable couscous', kcal: 440, carbsG: 76.0, proteinG: 14.0, fatG: 10.0, minutes: 25,
      allergens: ['gluten'], dietTypes: ['vegetarian', 'vegan', 'high-fibre'],
      ingredients: ['Couscous 120 g', 'Courgette 120 g', 'Aubergine 120 g', 'Chickpeas 100 g']),
  Recipe(id: 'local-23', name: 'Sweet potato and lentil stew', kcal: 420, carbsG: 62.0, proteinG: 18.0, fatG: 8.0, minutes: 35,
      allergens: [], dietTypes: ['vegetarian', 'vegan', 'high-fibre'],
      ingredients: ['Red lentils 150 g', 'Sweet potato 200 g', 'Onion 80 g', 'Cumin 1 tsp']),
  Recipe(id: 'local-24', name: 'Vegan chilli with rice', kcal: 545, carbsG: 82.0, proteinG: 20.0, fatG: 12.0, minutes: 40,
      allergens: [], dietTypes: ['vegetarian', 'vegan', 'high-fibre'],
      ingredients: ['Black beans 200 g', 'Kidney beans 100 g', 'Tomato 300 g', 'Rice 120 g']),
  Recipe(id: 'local-25', name: 'Quinoa and roasted vegetable bowl', kcal: 480, carbsG: 64.0, proteinG: 16.0, fatG: 16.0, minutes: 30,
      allergens: [], dietTypes: ['vegetarian', 'vegan', 'high-fibre'],
      ingredients: ['Quinoa 140 g', 'Courgette 120 g', 'Pepper 120 g', 'Olive oil 1 tbsp']),
];
